# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2021 ImmortalWrt.org

name: Build rootfs images

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Source branch"
        required: true
        default: "master"
      version:
        description: "Release version"
        required: true
        default: "snapshot"

jobs:
  build:
    name: Build rootfs image for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: armsr-armv7
            arch: arm_cortex-a15_neon-vfpv4
          - target: armsr-armv8
            arch: aarch64_generic

    steps:
      - name: Checkout docker repo
        uses: actions/checkout@v3

      - name: Download rootfs for ${{ matrix.target }}
        run: ./download_files.sh rootfs
        env:
          TARGET: ${{ matrix.target }}
          VERSION: ${{ github.event.inputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push rootfs image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.rootfs
          platforms: linux/amd64
          push: true
          tags: |
            jing2hang1105/imw-rootfs:${{ matrix.arch }}-${{ github.event.inputs.branch }}
            jing2hang1105/imw-rootfs:${{ matrix.arch }}-${{ github.event.inputs.version }}
            jing2hang1105/imw-rootfs:${{ matrix.target }}-${{ github.event.inputs.branch }}
            jing2hang1105/imw-rootfs:${{ matrix.target }}-${{ github.event.inputs.version }}

      - name: Push extra tags for snapshot
        if: ${{ github.event.inputs.version == 'snapshot' }}
        run: |
          docker tag jing2hang1105/imw-rootfs:${{ matrix.target }}-${{ github.event.inputs.version }} immortalwrt/rootfs:${{ matrix.arch }}
          docker tag jing2hang1105/imw-rootfs:${{ matrix.target }}-${{ github.event.inputs.version }} immortalwrt/rootfs:${{ matrix.target }}
          docker push jing2hang1105/imw-rootfs:${{ matrix.arch }}
          docker push jing2hang1105/imw-rootfs:${{ matrix.target }}

      - name: Push extra tags for x86-64
        if: ${{ matrix.target == 'x86-64' }}
        run: |
          docker pull immortalwrt/rootfs:${{ matrix.target }}-${{ github.event.inputs.version }}
          docker tag immortalwrt/rootfs:${{ matrix.target }}-${{ github.event.inputs.version }} immortalwrt/rootfs:${{ github.event.inputs.branch }}
          docker tag immortalwrt/rootfs:${{ matrix.target }}-${{ github.event.inputs.version }} immortalwrt/rootfs:${{ github.event.inputs.version }}
          docker push immortalwrt/rootfs:${{ github.event.inputs.branch }}
          docker push immortalwrt/rootfs:${{ github.event.inputs.version }}
